### ISSUE TITLE
Problem with running times and final VCF

### ISSUE THREAD

**Issue by miguel-correa92** [danielmoney/LinkImputeR#1]
I am currently working with LinkImputeR to do the imputation of a WGS dataset (the results of the accuracy analysis can be found attached to this email) and I am having trouble with the running times because I am working from a Cluster and therefore have limited time for a run of the imputing part of the program. I would like to run case #6, but it is exceeding the time limit (3 days). Is there a way to improve the running time from my end? like subdividing the VCF file by chromosomes and running each independently?

I have also found another issue. Whenever I run the imputation, some of the markers have a mistake that makes the file unreadable for other programs (e.g TASSEL 5). My solution so far has been to remove these sites (3 for case 7 and 2920 for case 9) as they are not many. The issue in concrete is the following piece of string "0../.0.0". Attached you can find three of such markers.

Thank you in advance for your help and your time.
[accuracy.txt](https://github.com/danielmoney/LinkImputeR/files/4029807/accuracy.txt)
[problem_markers_case_7.txt](https://github.com/danielmoney/LinkImputeR/files/4029830/problem_markers_case_7.txt)

**Comment by danielmoney** [comment]
The underlying imputation algorithm of LinkImputeR (LD-kNNi) was designed to be run across all chromosomes at once but, that said, I've heard of people running it per chromosome with good results when there is a large number of markers.  So if you're struggling with runtime I'd definitely recommend running per chromosome and see how it goes.

As for the mangled output would it be possible for you to provide the same 3 sites as they are in the original vcf?  I suspect it's a bug with how the sites are updated with the new information and seeing the original sites should help me get to the bottom of it.

**Comment by miguel-correa92** [comment]
Thanks for your quick response. 
Please find attached the three problem markers from the original vcf.


[filtered_markers.zip](https://github.com/danielmoney/LinkImputeR/files/4030743/filtered_markers.zip)

**Comment by danielmoney** [comment]
Just to give you an update.  The problem is being caused by the fact that some of your genotypes only have two fields, i.e. `./.:0,0`.  Now the vcf spec does allow trailing fields to be completely missing but at the moment it's causing LinkImputeR a problem and I need to work out how best to handle it (there are a couple of options that I think are available to me).  While I work on the bug fix if you want to get it running without this error then replacing the two field cases with the equivalent seven field genotype, i.e. `./.:0,0:0:.:.:.:0,0,0` should be a viable workaround for now.

You have highlighted another couple of bugs as well.  First of all java is doing internalisation and using `,` as the decimal separator in the output likelihoods and that's against the vcf spec which mandates `.` .  Second it is adding new fields to the end of the existing genotype without checking that all the previous fields are there so, in the case of truncated genotypes like caused the problem here, the fields end up misaligned.  I'll also fix these two bugs when fixing the main one.

Now I think I know what all the bugs are I hope to have a proper fix by the end of the week but I'm going to be travelling and at a conference so don't want to promise anythng.

**Comment by danielmoney** [comment]
Had more free time today than I was expecting so managed to do this bug fix.  A test version (1.2.3) is [here](http://www.danielmoney.co.uk/LinkImputeR.tar.gz).

Would be great if you could see if this works for you.  If it does I'll update everything officially.

**Comment by miguel-correa92** [comment]
I ran the new version with a small data set an now everything works perfectly.
Thank you very much.
Best regards
